# -*- coding: utf-8 -*-
"""graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v32gKtyUQK2tM7SPwPIQ08BGR4I91WZ3
"""

import matplotlib.pyplot as plt
hours = [1,2,3,4,5,6,7,8]
visitors = [50,60,65,70,90,120,110,130]
plt.plot(hours, visitors,
         color = "black",
         marker = "o",
         linestyle = "-",
         linewidth = 1,
         alpha = 1,
         label = "visitors")
plt.title("website visitors per hour")
plt.xlabel("Hour of Day")
plt.ylabel("Number of visitors")
plt.legend()
plt.grid(True,linestyle="--", alpha=0.5)
plt.show()

