# -*- coding: utf-8 -*-
"""graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v32gKtyUQK2tM7SPwPIQ08BGR4I91WZ3
"""

import matplotlib.pyplot as plt
hours = [1,2,3,4,5,6,7,8]
visitors = [50,60,65,70,90,120,110,130]
plt.plot(hours, visitors,
         color = "black",
         marker = "o",
         linestyle = "-",
         linewidth = 1,
         alpha = 1,
         label = "visitors")
plt.title("website visitors per hour")
plt.xlabel("Hour of Day")
plt.ylabel("Number of visitors")
plt.legend()
plt.grid(True,linestyle="--", alpha=0.5)
plt.show()

products=['Laptop','Mobile','Tablet','Headphones','Smart watch']
sales=[250,400,150,300,180]
plt.bar(products,sales,color='blue',edgecolor='black',alpha=0.5,width=0.8)
plt.title("Product Sales Comparison")
plt.xlabel("Products")
plt.ylabel("Units Sold")
plt.show()

marks=[45,45,60,72,68,80,90,55,67,70,
       85,40,60,75,78,82,95,50,52,65,
       58,36,37,69,71,88,39,55,63,59]
plt.hist(marks,bins=8,histtype='bar',color='blue',edgecolor='black',density=False)
plt.title("Marks Distribution")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.show()

brands=['Apple','Samsung','Xiaomi','Oppo','Vivo']
market_share=[30,20,25,10,15]
plt.pie(market_share,labels=brands,autopct="%d%%",startangle=180,colors=['red','blue','green','yellow','lightcoral'],explode=[0,0.3,0,0,0],shadow=True)
plt.title("Mobile Market Share")
plt.show()

ad_spend=[2,4,5,7,8,10,11,12]
sales=[27,25,28,35,40,48,50,52]
profit=[200,250,90,350,40,80,500,250]
colors=[8,1,2,3,5,6,7,4]
plt.scatter(ad_spend,sales,s=profit,c=colors,cmap='Reds',alpha=0.8,edgecolors='black',linewidths=1.2)
plt.title("Advertising Spend vs Sales (with Color & Size)", fontsize=14, fontweight="bold")
plt.xlabel("Ad Spend ($1000s)", fontsize=12)
plt.ylabel("Sales ($1000s)", fontsize=12)
plt.colorbar(label="Sales Value")
plt.grid(True, linestyle="--", alpha=0.2)
plt.show()

scores=[[70,85,90,92,88,76,95,9],
        [65,70,68,72,75,80,85,75],
        [90,92,94,96,88,91,89,93],
        [62,60,61,90,65,63,67,61],
        [70,85,96,75,8,52,66,88]]
plt.boxplot(scores,patch_artist=False,medianprops=dict(color='red',linewidth=2),whiskerprops=dict(color='green',linewidth=4),
            capprops=dict(color='blue',linewidth=2),notch=False,vert=False,labels=['A','B','C','D','E'])
plt.title("Exams Scores Distribution Across Classes")
plt.xlabel("Classes")
plt.ylabel("Scores")
plt.grid(True,linestyle='--',alpha=0.7)
plt.show()

days = [1,2,3,4,5,6,7]
visitors = [200,250,230,280,300,320,350]
plt.fill_between(days, visitors,color="skyblue",alpha=0.5,label="Website Visitors")
plt.plot(days, visitors,color="blue",linewidth=2)
plt.title("Website Visitors over a Week")
plt.xlabel("Days")
plt.ylabel("Visitors")
plt.show()

import matplotlib.pyplot as plt

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
sales = [120, 135, 150, 160, 170, 200, 220]
profit = [30, 40, 45, 50, 55, 70, 80]

plt.figure(figsize=(10, 8))

plt.subplot(2, 2, 1)
plt.plot(days, sales, marker="o", color="blue")
plt.title("Sales Over Days")
plt.grid(True)

plt.subplot(2, 2, 2)
plt.bar(days, sales, color="orange")
plt.title("Sales Bar Chart")

plt.subplot(2, 2, 3)
plt.scatter(sales, profit, color="green", s=100, edgecolors="black")
plt.title("Sales vs Profit")

plt.subplot(2, 2, 4)
plt.pie(sales, labels=days, autopct="%1.1f%%", startangle=90)
plt.title("Sales Distribution")

plt.tight_layout()
plt.show()

